
server:
  port: 8888
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/a-farsi/spring-config-repo
          search-paths: configs
          default-label: main
